# __________                    .___        _________
# \______   \_____    ____    __| _/____   /   _____/__________ __  _  ____  _  ______   ___________  ______
#  |     ___/\__  \  /    \  / __ |\__  \  \_____  \\____ \__  \\ \/ \/ /\ \/ \/ /    \_/ __ \_  __ \/  ___/
#  |    |     / __ \|   |  \/ /_/ | / __ \_/        \  |_> > __ \\     /  \     /   |  \  ___/|  | \/\___ \
#  |____|    (____  /___|  /\____ |(____  /_______  /   __(____  /\/\_/    \/\_/|___|  /\___  >__|  /____  >
#                \/     \/      \/     \/        \/|__|       \/                    \/     \/           \/

# Author: Morphie

# NOTE: These are in order of progression. Main parts to detect progression is the number starting at 0 as well as the "Type: MOB_NAME".
SpawnerUpgraders:
  0: # start of the progression from the base spawner.
    Name: "&2&lPig Spawner Upgrader" # Item Display Name
    Spawner: "CHICKEN"
    Type: "PIG" # Type of spawner upgrader it is. This must be the Mobs Spawner type.
    Item: "PIG_SPAWN_EGG" # Item for the spawner changer
    Glow: true # Glow effect on item
    CustomModelData: 0 # Custom model data for the spawner changer
    Lore: # Lore for the spawner changer
      - "&a&l| &7Right&8-&7Click a spawner or drag and drop"
      - "&a&l| &7onto a spawner in your inventory to upgrade it!"
  1:
    Name: "&2&lCow Spawner Upgrader"
    Spawner: "PIG"
    Type: "COW"
    Item: "COW_SPAWN_EGG"
    Glow: true
    CustomModelData: 0
    Lore:
      - "&a&l| &7Right&8-&7Click a spawner or drag and drop"
      - "&a&l| &7onto a spawner in your inventory to upgrade it!"