# __________                    .___        _________
# \______   \_____    ____    __| _/____   /   _____/__________ __  _  ____  _  ______   ___________  ______
#  |     ___/\__  \  /    \  / __ |\__  \  \_____  \\____ \__  \\ \/ \/ /\ \/ \/ /    \_/ __ \_  __ \/  ___/
#  |    |     / __ \|   |  \/ /_/ | / __ \_/        \  |_> > __ \\     /  \     /   |  \  ___/|  | \/\___ \
#  |____|    (____  /___|  /\____ |(____  /_______  /   __(____  /\/\_/    \/\_/|___|  /\___  >__|  /____  >
#                \/     \/      \/     \/        \/|__|       \/                    \/     \/           \/

# Author: Morphie

SpawnerUpgrader:
  ItemName: 'COMPASS'
  CustomModelID: 0
  DisplayName: '&2&lSpawner Upgrader'
  Lore:
    - '&a&l| &7Right click a spawner OR drag and drop'
    - '&a&l| &7onto a spawner in your inventory to upgrade!'
  Progression:
    - ''