name: PandaSpawners
version: 1.0.0
main: morphie.gg.pandaspawners.PandaSpawners
author: Morphie
api-version: 1.20
commands:
  pandaspawners:
    description: Main command for PandaSpawners.
    usage: /<command>
    aliases: [pspawners, ps]